# Generated by Django 4.1.3 on 2022-12-05 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_created_producto_updated'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='pedido_id',
        ),
        migrations.RemoveField(
            model_name='lineapedido',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(null=True, blank=True,  on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(null=True, blank=True,  on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
            preserve_default=False,
        ),
    ]
